import '../styles/globals.css'


import Header  from './components/Header'
import Cards from './components/Cards'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  )
}
